apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-tcj5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: componentb-devfile-sample-go-basic-private-devfile-nested-tcj5
    app.kubernetes.io/part-of: mc-golang-nested
  name: componentb-devfile-sample-go-basic-private-devfile-nested-tcj5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-tcj5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-tcj5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gmtn-tenant/mc-golang-nested/componentb-devfile-sample-go-basic-private-devfile-nested-tcj5@sha256:b577ddf460d4c4b2d0ba6456a2e3521e688dae329d1dee42909b13f8ac3378e7
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
